---

- name: "Java prerequisites"
  block:

  - name: add apt-key to local repository
    shell: |
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
      apt-add-repository 'deb http://repos.azulsystems.com/ubuntu stable main'

  - name: apt update and install zulu-13
    shell: |
      apt-get update -y
      apt-get install zulu-13  -y

  - name: verify java version
    shell: java --version
    register: result

  - name: debug version
    debug:
      var: result.stdout

  tags:
  - java
  - never

